# Generated by Django 3.0.1 on 2020-12-08 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignName', models.CharField(max_length=100, unique=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignName', models.CharField(max_length=100, unique=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('sub_category', models.TextField(default='NA')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeID', models.CharField(max_length=150)),
                ('name', models.CharField(default='NA', max_length=150)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.CharField(default='NA', max_length=100)),
                ('DOB', models.CharField(default='NA', max_length=10)),
                ('gender', models.CharField(default='NA', max_length=6)),
                ('entry_type', models.CharField(max_length=10)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='customerQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.CharField(max_length=80)),
                ('customer_contact', models.IntegerField()),
                ('customer_DOB', models.CharField(max_length=15)),
                ('customer_message', models.TextField()),
                ('source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='store_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeID', models.CharField(max_length=150, unique=True)),
                ('store_name', models.CharField(max_length=80, unique=True)),
                ('store_location', models.CharField(max_length=30)),
                ('store_town', models.CharField(max_length=30)),
                ('store_city', models.CharField(max_length=30)),
                ('store_state', models.CharField(max_length=30)),
                ('store_category', models.CharField(max_length=100)),
                ('store_subcategory', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store_supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(default='NA', max_length=50)),
                ('supervisor_contact', models.CharField(default='NA', max_length=12)),
                ('supervisor_email', models.CharField(default='NA', max_length=100)),
                ('supervisor_gender', models.CharField(default='NA', max_length=30)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tier_collective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tierType', models.CharField(max_length=10)),
                ('tierRuleNo', models.IntegerField()),
                ('shop_start_amt', models.IntegerField()),
                ('shop_end_amt', models.IntegerField()),
                ('time_period', models.IntegerField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tier_individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tierType', models.CharField(max_length=10)),
                ('tierRuleNo', models.IntegerField()),
                ('store_ID', models.CharField(max_length=30)),
                ('shop_start_amt', models.IntegerField()),
                ('shop_end_amt', models.IntegerField()),
                ('time_period', models.IntegerField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='store_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_image', models.ImageField(upload_to='SuperVisorImages/')),
                ('manager_name', models.CharField(max_length=50)),
                ('manager_contact', models.IntegerField()),
                ('user_unique_id', models.CharField(max_length=30)),
                ('manager_email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('manager_password', models.CharField(max_length=30)),
                ('DOB', models.CharField(blank=True, default='01-01-2000', max_length=12, null=True)),
                ('entry_type', models.CharField(max_length=12)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.store_detail')),
            ],
        ),
        migrations.CreateModel(
            name='SmsSubCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allsms', models.TextField(default='NA')),
                ('text', models.TextField(default='NA')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('CampaignName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.CampaignSms')),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.IntegerField()),
                ('password_saved', models.CharField(max_length=100)),
                ('storeID', models.CharField(max_length=150, unique=True)),
                ('entry_type', models.CharField(max_length=12)),
                ('profile_pic', models.ImageField(upload_to='SuperVisorImages/')),
                ('DOB', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSubCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allEmails', models.TextField(default='NA')),
                ('text', models.TextField(default='NA')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('CampaignName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.CampaignEmail')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerShopData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeID', models.CharField(max_length=150)),
                ('invoice', models.CharField(max_length=100, unique=True)),
                ('amount', models.FloatField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.CustomerData')),
            ],
        ),
    ]
