# Generated by Django 3.1.2 on 2020-12-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customershopdata',
            name='invoice',
            field=models.CharField(max_length=100),
        ),
    ]
