# Generated by Django 3.1.1 on 2020-12-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201217_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='DOM',
            field=models.CharField(default='NA', max_length=6),
        ),
    ]
