# Generated by Django 3.1.1 on 2020-12-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_customerdata_dom'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_manager',
            name='statusflag',
            field=models.BooleanField(default=1),
        ),
    ]
