# Generated by Django 3.1.1 on 2020-12-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201218_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulelist',
            name='emailSubject',
        ),
    ]
