# Generated by Django 3.1.1 on 2020-12-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_schedulelist_emailsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='scheduleSMSList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailList', models.TextField(default='NA')),
                ('emailText', models.TextField(default='NA')),
            ],
        ),
        migrations.RenameModel(
            old_name='scheduleList',
            new_name='scheduleEmailList',
        ),
    ]
