# Generated by Django 2.2.10 on 2021-01-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210104_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='store_manager',
            name='manager_contact',
            field=models.CharField(max_length=10),
        ),
    ]
