# Generated by Django 2.2.10 on 2021-07-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='supervisorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_image', models.ImageField(upload_to='SuperVisorImages/')),
                ('supervisor_name', models.CharField(max_length=50)),
                ('supervisor_contact', models.CharField(max_length=10)),
                ('supervisor_unique_id', models.CharField(max_length=30)),
                ('supervisor_email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('supervisor_password', models.CharField(max_length=30)),
                ('store_array', models.CharField(max_length=150)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='storeID',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
