# Generated by Django 2.2.10 on 2021-07-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210725_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='storeGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=50, unique=True)),
                ('groupDescription', models.TextField()),
                ('store_array', models.CharField(max_length=150)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
