# Generated by Django 2.2.10 on 2021-07-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_storegroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='storegroups',
            name='groupID',
            field=models.CharField(default='00', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
