# Generated by Django 2.2.10 on 2021-07-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_storegroups_groupid'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportID', models.CharField(max_length=50, unique=True)),
                ('method', models.CharField(max_length=30)),
                ('selected_Conditions', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('storeGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.storeGroups')),
            ],
        ),
    ]
