# Generated by Django 2.2.10 on 2021-08-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_sharereport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharereport',
            old_name='reportFK',
            new_name='report_FK',
        ),
    ]
