# Generated by Django 2.2.10 on 2021-08-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_store_shared_record_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_shared_record_history',
            name='supervisor_email',
            field=models.CharField(max_length=50),
        ),
    ]
