# Generated by Django 2.2.10 on 2021-08-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20210810_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storegroups',
            name='store_array',
            field=models.TextField(),
        ),
    ]
