# Generated by Django 2.2.10 on 2021-08-29 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20210819_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='supervisor_noOfVisit_Report_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportID', models.CharField(max_length=50, unique=True)),
                ('selected_stores', models.TextField()),
                ('dateRange', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('supervisor_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.supervisorDetails')),
            ],
        ),
        migrations.CreateModel(
            name='supervisor_amountOfPurchase_Report_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportID', models.CharField(max_length=50, unique=True)),
                ('selected_stores', models.TextField()),
                ('dateRange', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('supervisor_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.supervisorDetails')),
            ],
        ),
    ]
